[versions]
app-version-code = "1"
app-version-name = "1.0.0"
android-compileSdk = "34"
android-minSdk = "24"
agp = "8.3.0-alpha11"
kotlin = "1.9.10"
compose-plugin = "1.5.10-rc01"
compose-compiler = "1.5.3"
voyager = "1.0.0-rc07"
kotlinInject = "0.6.1"
settings = "1.1.0"

[libraries]
androidx-appcompat = { module = "androidx.appcompat:appcompat", version = "1.6.1" }
androidx-activity-compose = { module = "androidx.activity:activity-compose", version = "1.8.0" }
androidx-core = { module = "androidx.core:core-ktx", version = "1.12.0" }
androidx-datastore = { module = "androidx.datastore:datastore-preferences", version = "1.0.0" }

kotlin-inject-compiler = { module = 'me.tatarka.inject:kotlin-inject-compiler-ksp', version.ref = 'kotlinInject' }
kotlin-inject-runtime = { module = 'me.tatarka.inject:kotlin-inject-runtime', version.ref = 'kotlinInject' }
kotlin-viewmodel-core = { module = "com.rickclephas.kmm:kmm-viewmodel-core", version = "1.0.0-ALPHA-14"}

imageloader = { module = "io.github.qdsfdhvh:image-loader", version = "1.6.8" }

logging = { module = "org.lighthousegames:logging", version = "1.3.0" }

settings = { module = "com.russhwolf:multiplatform-settings", version.ref = "settings" }
settings-coroutines = { module = "com.russhwolf:multiplatform-settings-coroutines", version.ref = "settings" }
settings-datastore = { module = "com.russhwolf:multiplatform-settings-datastore", version.ref = "settings" }

voyager-navigator = { module = "cafe.adriel.voyager:voyager-bottom-sheet-navigator", version.ref = "voyager" }
voyager-transitions = { module = "cafe.adriel.voyager:voyager-transitions", version.ref = "voyager" }
voyager-navigator-tabs = { module = "cafe.adriel.voyager:voyager-tab-navigator", version.ref = "voyager" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
android-library = { id = "com.android.library", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
compose = { id = "org.jetbrains.compose", version.ref = "compose-plugin" }
ksp = { id = "com.google.devtools.ksp", version = "1.9.10-1.0.13" }
buildConfig = { id = "com.github.gmazzo.buildconfig", version = "4.1.2" }
